
let myAge = 16; 

let earlyYears = 2; 

earlyYears *= 10.5;

let laterYears = myAge - 2;

laterYears *= 4;

console.log(earlyYears); 
console.log(laterYears);

let myAgeInDogYears = earlyYears + laterYears; 

let myName = "André";
myName = myName.toLowerCase(); 


console.log(`Meu nome é ${myName}. Tenho ${myAge} anos em anos humanos, que são ${myAgeInDogYears} anos em anos de cão.`);
